import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./ui/fonts";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { SearchProvider } from "@/contexts/SearchContext";
import LogoBar from "@/components/LogoBar/LogoBar";

export const metadata: Metadata = {
  title: "Frente e Verso",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SearchProvider>
      <html lang="en">
        <body className={roboto.className}>
          <Header />
          <div style={{display: "flex"}}>
            <LogoBar />
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </SearchProvider>
  );
}